### ISSUE TITLE
救救孩子

### ISSUE THREAD

**Issue by taneui908** [perhamer/Find_Love_MusicCloud#6]
F:\Python\Scripts\python.exe F:/sim/下载/Find_Love_MusicCloud-master/playlist_by_user.py
Traceback (most recent call last):
  File "F:/sim/下载/Find_Love_MusicCloud-master/playlist_by_user.py", line 4, in <module>
    import sql
  File "F:\sim\下载\Find_Love_MusicCloud-master\sql.py", line 6, in <module>
    connection = pymysql.connect(host='localhost',
  File "F:\Python\lib\site-packages\pymysql\connections.py", line 353, in __init__
    self.connect()
  File "F:\Python\lib\site-packages\pymysql\connections.py", line 633, in connect
    self._request_authentication()
  File "F:\Python\lib\site-packages\pymysql\connections.py", line 932, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
  File "F:\Python\lib\site-packages\pymysql\_auth.py", line 239, in caching_sha2_password_auth
    pkt = conn._read_packet()
  File "F:\Python\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "F:\Python\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "F:\Python\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database 'cloudmusic'")

Process finished with exit code 1

o(╥﹏╥)o

**Comment by perhamer** [comment]
首先要建库
